version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tfg-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/data
    networks:
      - tfg-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tfg-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tfg-network

networks:
  tfg-network:
    driver: bridge
